No need to fiddle with parity's $LOADPATH
`brew upgrade parity` (from 0.3.1) gave me this result:

```
==> Upgrading 1 outdated package, with result:
parity 0.5.0
==> Upgrading parity
==> Downloading https://github.com/croaky/parity/releases/download/v0.5.0/parity-0.5.0-osx.tar.gz
Already downloaded: /Library/Caches/Homebrew/parity-0.5.0.tar.gz
Error: No such file or directory - lib/parity.rb
```

The fix is to just not touch `lib/parity.rb`, since it runs without it.